package org.example.waterdelivery.entity.enums;

public enum TelegramState {
    SHARE_CONTACT, SELECT_REGION, SHARE_LOCATION, WAITING, CABINET, SELECT_BOTTLE_TYPE, START_ORDERING, SELECT_BOTTLE_NUMBER, CONFIRM_ORDER, CREATE_ORDER, START
}
